update schema
myriadsocial/myriad-api pull request #51
Opened 2021-06-30 04:01 UTC by abdulhakim2902

2021-07-06 04:41 UTC, rei-gun requested changes

2021-07-06 04:41 UTC, rei-gun commented on src/controllers/user.controller.ts
> +// import {Keyring} from '@polkadot/api';
mendingan all of the polkadot logic di extract ke file terpisah terus di comment 1 line aja

2021-07-07 13:58 UTC, rei-gun reviewed
Love what you did with application.ts!

2021-07-07 15:00 UTC, rei-gun requested changes

2021-07-07 15:00 UTC, rei-gun commented on src/seed-data/tokens.json
> +        "id": "DOT",
sebenarnya DOT is a coin, not a token right?

2021-07-07 16:47 UTC, abdulhakim2902 commented on src/controllers/transaction.controller.ts
> +  async sentMyriadReward(userId: string):Promise<void> {
Okay, mau kpn?

2021-07-07 16:49 UTC, abdulhakim2902 commented on src/controllers/transaction.controller.ts
> +      const queue = await this.queueRepository.create({
Semacam queue untuk nambah block di blockchain biar ngga ada konflik. Di awal kepikiran mau pake kepikiran yg sejenis RabbitMQ, tp gw nya masih bingung. Jadi sementara gw buat manual queue, yang nomor antriannya di simpan DB.

2021-07-08 09:56 UTC, rei-gun approved these changes

2021-07-08 10:20 UTC, rei-gun approved these changes

2021-07-08 10:21 UTC, rei-gun approved these changes

2021-07-08 10:22 UTC, merged